repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: pretty-format-json
        args: [ --autofix ]
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: requirements-txt-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: fix-encoding-pragma

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-docstrings ]
        exclude: ^test/|src_models/

  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
