name: finances
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - flake8
    - python-dotenv>=0.5.1
    - pytest
    - pytest-cov
    - black
    - -r requirements.txt
